<?php

$usuarios = [
    ['nombre' => 'Alejandra Patricia', 'apellidos' => 'Ponce Garcia', 'correo' => 'alejandra94.ponce@gmail.com', 'celular' => '3332235351'],
    ['nombre' => 'Alma Leticia', 'apellidos' => 'Aguilar Peña', 'correo' => 'aguilarsofiaamor04@gmail.com', 'celular' => '3310058089'],
    ['nombre' => 'Alondra Sujey', 'apellidos' => 'Gallegos González', 'correo' => 'asgallegosg@hotmail.com', 'celular' => '3310303057'],
    ['nombre' => 'Ana Isabel', 'apellidos' => 'Peña Flores', 'correo' => 'anaisapf2027@gmail.com', 'celular' => '3331044978'],
    ['nombre' => 'Axel Alexis', 'apellidos' => 'García Aguirre', 'correo' => 'alexis_garcia@live.com.mx', 'celular' => '3325803460'],
    ['nombre' => 'Catia Sofia', 'apellidos' => 'Peña Ceja', 'correo' => 'katyspc27@gmail.com', 'celular' => '3335736163'],
    ['nombre' => 'Cecilia del Carmen', 'apellidos' => 'Báez Ascencio', 'correo' => 'cecycarmenbaez@hotmail.com', 'celular' => '3337236921'],
    ['nombre' => 'Claudia Gabriela', 'apellidos' => 'Altamirano Mendoza', 'correo' => 'holaclaudia.altamirano@gmail.com', 'celular' => '3311216643'],
    ['nombre' => 'Claudia Ivette', 'apellidos' => 'Quintero Silva', 'correo' => 'netosarevalos@gmail.com', 'celular' => '3327632447'],
    ['nombre' => 'Dante Alberto', 'apellidos' => 'Gonzalez Serna', 'correo' => 'giannapasteles39@gmail.com', 'celular' => '3312617862'],
    ['nombre' => 'Francisco Javier', 'apellidos' => 'Valle Perez ', 'correo' => 'fumilvallepb@gmail.com', 'celular' => '3334941927'],
    ['nombre' => 'Francisco Lara', 'apellidos' => 'Sanchez', 'correo' => 'franciscolaes@gmail.com', 'celular' => '3318045207'],
    ['nombre' => 'Gabriela Avila', 'apellidos' => 'Valdivia', 'correo' => 'gabrielaavilavaldivia@gmail.com', 'celular' => '1111111111'],
    ['nombre' => 'Gabriela', 'apellidos' => 'García Mendoza', 'correo' => 'biselesytempladosgarcia@hotmail.com', 'celular' => '3312648246'],
    ['nombre' => 'Gardenia', 'apellidos' => 'Soto Salazar', 'correo' => 'misti2409@hotmail.com', 'celular' => '3310464129'],
    ['nombre' => 'Jesús Ramón', 'apellidos' => 'Silva Avalos', 'correo' => 'jesusjessesilva@gmail.com', 'celular' => '4621395553'],
    ['nombre' => 'Guadalupe Lizbeth', 'apellidos' => 'Perez Huerta ', 'correo' => 'guadalupe.perez.2158@gmail.com', 'celular' => '3335793806'],
    ['nombre' => 'Hector Hugo', 'apellidos' => 'Vazquez Ibarra', 'correo' => 'ing.hugoibarra7@gmail.com', 'celular' => '3328691880'],
    ['nombre' => 'Heriberto Vega', 'apellidos' => 'Villaseñor', 'correo' => 'betovovegamx@gmail.com', 'celular' => '3316069585'],
    ['nombre' => 'Ilenia Maribel', 'apellidos' => 'Esparza Lomeli', 'correo' => 'evlimileile@gmail.com', 'celular' => '3311873225'],
    ['nombre' => 'Jessica', 'apellidos' => 'Moran Garcia', 'correo' => 'moran.jessica2nov@gmail.com', 'celular' => '3330438073'],
    ['nombre' => 'Jorge Edgardo', 'apellidos' => 'Cisneros Villaseñor', 'correo' => 'jorgeedgardocisnerosvillasenor@gmail.com', 'celular' => '3324955516'],
    ['nombre' => 'Luz Miriam', 'apellidos' => 'Trigo Estrada', 'correo' => 'luztries5@hotmail.com', 'celular' => '3311348695'],
    ['nombre' => 'Ma. del Carmen', 'apellidos' => 'Rosas Gonzalez', 'correo' => 'mariadelcarmenrosasgonzalez0@hotmail.com', 'celular' => '3317694847'],
    ['nombre' => 'Maria del Rosario', 'apellidos' => 'Mendoza Martinez', 'correo' => 'chayotinmendoza@gmail.com', 'celular' => '3313281250'],
    ['nombre' => 'Maria Yadira', 'apellidos' => 'Jasbeth Vazquez Martinez ', 'correo' => 'minavm06@gmail.com', 'celular' => '3335823408'],
    ['nombre' => 'Maricela Gaspar', 'apellidos' => 'Zambrano', 'correo' => 'mari_248@hotmail.com', 'celular' => '3319921982'],
    ['nombre' => 'Martha', 'apellidos' => 'Alonso Gomez', 'correo' => 'nadiadaesilva@gmail.com', 'celular' => '3311476473'],
    ['nombre' => 'Miguel Angel', 'apellidos' => 'Perez Maldonado Mendoza', 'correo' => 'miguelitodomico@gmail.com', 'celular' => '3320806881'],
    ['nombre' => 'Nelida', 'apellidos' => 'Valenzuela Rosales', 'correo' => 'mera541zoe@gmail.com', 'celular' => '3331846254'],
    ['nombre' => 'Norma Esperanza', 'apellidos' => 'Trejo Ruiz', 'correo' => 'papelerianorsui@hotmail.com', 'celular' => '3332363647'],
    ['nombre' => 'Norma Leticia', 'apellidos' => 'Orozco Rodriguez', 'correo' => 'norlet_oro.789@hotmail.com', 'celular' => '3312682146'],
    ['nombre' => 'Oswaldo', 'apellidos' => 'Gama Ortiz', 'correo' => 'chochegaor@gmail.com', 'celular' => '3318576000'],
    ['nombre' => 'Salvador', 'apellidos' => 'Peña Flores', 'correo' => 'penamenasalvador@gmail.com', 'celular' => '3333277994'],
    ['nombre' => 'Sandra Patricia', 'apellidos' => 'Rojas Avila', 'correo' => 'paty_rojas@hotmail.com', 'celular' => '3325064379'],
    ['nombre' => 'Saskia Margarita', 'apellidos' => 'Panameño Gomez', 'correo' => 'sksfashionevents@gmail.com', 'celular' => '3333770163'],
    ['nombre' => 'Teresita de Jesus', 'apellidos' => 'Ruelas Chávez', 'correo' => 'teresaemili1803@gmail.com', 'celular' => '3326597875'],
    ['nombre' => 'Victor Eduardo', 'apellidos' => 'Benicio Díaz ', 'correo' => 'vicedbenicio@gmail.com', 'celular' => '3337203174'],
    ['nombre' => 'Victor Manuel', 'apellidos' => 'Hernandez Ruvalcaba', 'correo' => 'modametalic@gmail.com', 'celular' => '3311968637'],
    ['nombre' => 'Francisco', 'apellidos' => 'Plascencia Gallardo', 'correo' => 'plascenciagf@gmail.com', 'celular' => '3334442105'],
    ['nombre' => 'Gabriel', 'apellidos' => 'Tejeda Rodriguez', 'correo' => 'gabo.atejeda@gmail.com', 'celular' => '3318383818'],
    ['nombre' => 'Maria Irene', 'apellidos' => 'Perez Nuñez', 'correo' => 'irenepznz@gmail.com', 'celular' => '3311542387'],
    ['nombre' => 'Marisela', 'apellidos' => 'Zertuche Ochoa', 'correo' => 'marysanzer.77@gmail.com', 'celular' => '3314533755'],
    ['nombre' => 'Ramon', 'apellidos' => 'Tarula Esparza', 'correo' => 'martelsoto@gmail.com', 'celular' => '3317384170']
];